services:
  wireguard-client:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: tracker-wireguard-client
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - "127.0.0.1:8080:8080"
      - "5000:5000"
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Amsterdam
    volumes:
      - ./wireguard-client:/config
      - /lib/modules:/lib/modules:ro

  tracker:
    image: ghcr.io/tinlas03-2025-vt/tracking-module:latest
    container_name: tracking-module
    restart: unless-stopped
    network_mode: service:wireguard-client
    depends_on:
      - wireguard-client
    volumes:
      - ./cyclonedds:/cyclonedds:ro
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///cyclonedds/client.xml

      - CAMERA_INDEX=0
      - CAMERA_PROFILE=sotp_cam
      - REFERENCE_TAG_0=0
      - REFERENCE_TAG_1=1
      - TARGET_TAGS=2:robot_2,3:robot_3,4:robot_4,5:robot_5
      - T0X=-0.3
      - T0Y=-0.3
      - T1X=10.3
      - T1Y=10.3
      - OUTPUT_TOPIC=/cam/pos
    devices:
      - /dev/video5:/dev/video0
      - /dev/dri:/dev/dri
    command: >
      bash -lc "
      source /opt/ros/humble/setup.bash &&
      until [ -e /sys/class/net/wg0 ] && ip addr show wg0 | grep -q 'inet 10.13.13.' && ip route get 10.13.13.1 >/dev/null 2>&1; do
        echo 'waiting for contained wg0 and route to 10.13.13.1...';
        sleep 1;
      done;
      echo 'tracker contained wg0 ready';
      ip addr show wg0;
      python3 src/main.py --show"
